PRAGMA foreign_keys = ON;
CREATE TABLE faculties (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, slug TEXT NOT NULL UNIQUE);
CREATE TABLE departments (id INTEGER PRIMARY KEY AUTOINCREMENT, faculty_id INTEGER NOT NULL REFERENCES faculties(id), name TEXT NOT NULL, slug TEXT NOT NULL, UNIQUE(faculty_id,name));
CREATE INDEX idx_department_name ON departments(name);
CREATE TABLE professors (id INTEGER PRIMARY KEY, department_id INTEGER REFERENCES departments(id), name_fa TEXT NOT NULL, academic_rank TEXT, official_profile_url TEXT, is_active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX idx_professor_name ON professors(name_fa);
CREATE INDEX idx_professor_department ON professors(department_id,is_active);
CREATE TABLE courses (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, normalized_name TEXT NOT NULL UNIQUE);
CREATE TABLE professor_courses (professor_id INTEGER NOT NULL REFERENCES professors(id) ON DELETE CASCADE, course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE, PRIMARY KEY(professor_id,course_id));
CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, password_hash TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', created_at TEXT NOT NULL, last_login_at TEXT);
CREATE TABLE reviews (id INTEGER PRIMARY KEY AUTOINCREMENT, professor_id INTEGER NOT NULL REFERENCES professors(id), user_id INTEGER REFERENCES users(id) ON DELETE SET NULL, display_mode TEXT NOT NULL, display_name TEXT, body TEXT NOT NULL, course_name TEXT, term_label TEXT, course_type TEXT, recommended INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'published', moderation_flags TEXT, technical_hash TEXT, duplicate_hash TEXT NOT NULL, created_at TEXT NOT NULL, published_at TEXT, updated_at TEXT);
CREATE INDEX idx_reviews_professor_public ON reviews(professor_id,status,created_at);
CREATE INDEX idx_reviews_professor_course ON reviews(professor_id,course_name,status);
CREATE INDEX idx_reviews_duplicate ON reviews(professor_id,duplicate_hash);
CREATE INDEX idx_reviews_identity_time ON reviews(technical_hash,created_at);
CREATE TABLE review_ratings (review_id INTEGER NOT NULL REFERENCES reviews(id) ON DELETE CASCADE, criterion TEXT NOT NULL, score INTEGER NOT NULL CHECK(score BETWEEN 1 AND 5), PRIMARY KEY(review_id,criterion));
CREATE INDEX idx_ratings_criterion_score ON review_ratings(criterion,score);
CREATE TABLE votes (review_id INTEGER NOT NULL REFERENCES reviews(id) ON DELETE CASCADE, voter_hash TEXT NOT NULL, value INTEGER NOT NULL CHECK(value IN (-1,1)), created_at TEXT NOT NULL, updated_at TEXT, PRIMARY KEY(review_id,voter_hash));
CREATE TABLE reports (id INTEGER PRIMARY KEY AUTOINCREMENT, review_id INTEGER NOT NULL REFERENCES reviews(id) ON DELETE CASCADE, reporter_hash TEXT NOT NULL, reason TEXT NOT NULL, details TEXT, status TEXT NOT NULL DEFAULT 'open', created_at TEXT NOT NULL, resolved_at TEXT, UNIQUE(review_id,reporter_hash));
CREATE INDEX idx_reports_status_time ON reports(status,created_at);
CREATE TABLE moderation_actions (id INTEGER PRIMARY KEY AUTOINCREMENT, review_id INTEGER REFERENCES reviews(id) ON DELETE SET NULL, action TEXT NOT NULL, reason TEXT NOT NULL, previous_status TEXT, new_status TEXT, admin_hash TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE rate_limits (action TEXT NOT NULL, identity_hash TEXT NOT NULL, window_start INTEGER NOT NULL, attempts INTEGER NOT NULL DEFAULT 1, expires_at TEXT NOT NULL, PRIMARY KEY(action,identity_hash,window_start));
CREATE INDEX idx_rate_expiry ON rate_limits(expires_at);
CREATE TABLE professor_stats (professor_id INTEGER PRIMARY KEY REFERENCES professors(id) ON DELETE CASCADE, review_count INTEGER NOT NULL DEFAULT 0, avg_overall REAL, recommend_percent REAL, stats_json TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE professor_change_requests (id INTEGER PRIMARY KEY AUTOINCREMENT, professor_id INTEGER REFERENCES professors(id) ON DELETE SET NULL, requester_hash TEXT NOT NULL, request_type TEXT NOT NULL, details TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open', created_at TEXT NOT NULL);
